### ISSUE TITLE
dependency node-cassandra-cql is no longer supported

### ISSUE THREAD

**Issue by ckross01** [jorgebay/winston-cassandra#1]
node-cassandra-cql is a deprecated cassandra node driver, they recommend switching to the https://github.com/datastax/nodejs-driver.

**Comment by jorgebay** [comment]
Im the developer on all the projects (node-cassandra-cql and datastax driver) :smile: but I haven't got time to update this project...
If you send a pull request, I will merge it!

**Comment by ckross01** [comment]
Fantastic I will work on that pr.
