### ISSUE TITLE
Change the npm package version to 0.3.0

### ISSUE THREAD

**Issue by ivanst-stoyanov** [jorgebay/winston-cassandra#5]
Hi @jorgebay 

Can you change the npm package verion to 0.3.0. It is still 0.2.0 and the latest changes are not there.

Thanks.

**Comment by jorgebay** [comment]
Published to npm and tagged: https://github.com/jorgebay/winston-cassandra/releases/tag/v0.3.0

Thanks @ivanst-stoyanov
